'use strict';
// Product regression: password login, one-time signup verification and explicit recovery.
// Real application handlers, parsed DOM and fake Supabase responses. No real email sent.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawnSync}=require('node:child_process');
const {parseHTML}=require('linkedom');
const {cloudRuntime,clone}=require('./review/harness.cjs');
const results=[],eq=(a,b)=>assert.deepEqual(clone(a),clone(b));
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message,stack:e.stack.split('\n').slice(0,4)});}}
const dom=html=>parseHTML('<html><body>'+html+'</body></html>').document;
const form=(kind,values)=>{const d=dom('<form data-cloud-form="'+kind+'">'+Object.keys(values).map(id=>'<input id="'+id+'">').join('')+'<button type="submit">Gönder</button></form>');for(const[id,v]of Object.entries(values)){d.getElementById(id).value=typeof v==='boolean'?'':v;d.getElementById(id).checked=v===true;}return d.querySelector('form');};
const email='member@example.invalid',password='A-test-pass-1!';
const signup=(extra={})=>form('signup',{authEmail:email,authName:'Test Member',authPassword:password,authPasswordConfirm:password,authConsent:true,...extra});
const login=(extra={})=>form('login',{authEmail:email,authPassword:password,...extra});
const button=action=>({dataset:{cloudAction:action}});
const deferred=()=>{let resolve;return{promise:new Promise(r=>{resolve=r}),resolve:v=>resolve(v)}};
const userSession=()=>({user:{id:'verified-member',email}});
function fakeClient(overrides={}){
  const calls=[];
  const auth={};
  for(const name of ['signInWithPassword','signInWithOtp','signUp','resend','verifyOtp','resetPasswordForEmail','updateUser','signOut','getSession']){
    auth[name]=async data=>{calls.push({name,data:clone(data??null)});if(overrides[name])return overrides[name](data);return {data:{session:name==='signInWithPassword'?userSession():null},error:null};};
  }
  auth.onAuthStateChange=()=>({data:{subscription:{unsubscribe(){}}}});
  const client={auth,from(){const q={select(){return q},eq(){return q},maybeSingle:async()=>({data:null,error:null})};return q;}};
  return {client,calls,count:name=>calls.filter(x=>x.name===name).length};
}
async function authRuntime(overrides={}){const f=fakeClient(overrides),r=await cloudRuntime(f.client);r.c.setContext({session:null});return {...r,...f};}
(async()=>{
await test('Login renders email plus one current-password field and no code form',async()=>{const r=await authRuntime();r.c.renderAuth('login');const d=dom(r.elements.authLayer.innerHTML);assert.equal(d.querySelectorAll('input[type=password]').length,1);assert.equal(d.querySelector('#authPassword').getAttribute('autocomplete'),'current-password');assert.equal(d.querySelector('#authEmail').getAttribute('autocomplete'),'username');assert.equal(d.querySelector('button[type=submit]').textContent,'Giriş yap');assert.equal(d.querySelector('#authOtp'),null);assert.ok(!d.body.textContent.includes('giriş kodu'));});
await test('Signup renders two new-password fields, consent and code explanation',async()=>{const r=await authRuntime();r.c.renderAuth('signup');const d=dom(r.elements.authLayer.innerHTML);assert.equal(d.querySelectorAll('input[type=password][autocomplete="new-password"]').length,2);assert.ok(d.querySelector('#authConsent'));assert.match(d.body.textContent,/Sonraki girişlerinde e-posta adresini ve şifreni kullan/);});
await test('Successful password login activates session without sending email or creating account',async()=>{const r=await authRuntime();await r.c.handleForm(login({authEmail:' '+email+' ',authPassword:' pass with spaces '}));eq(r.calls,[{name:'signInWithPassword',data:{email,password:' pass with spaces '}}]);assert.equal(r.c.session.user.id,'verified-member');assert.equal(dom(r.elements.authLayer.innerHTML).querySelector('#authOtp'),null);assert.ok(![...r.store.values()].some(x=>x.includes('pass with spaces')));});
await test('Missing or malformed email and empty password are rejected before any API call',async()=>{const r=await authRuntime();await r.c.handleForm(login({authEmail:'bad@'}));await r.c.handleForm(login({authEmail:''}));await r.c.handleForm(login({authPassword:''}));assert.equal(r.calls.length,0);assert.equal(r.c.session,null);assert.match(r.elements.authLayer.innerHTML,/Şifreni yaz/);});
await test('Existing short passwords are sent to server unchanged instead of blocked by signup rules',async()=>{const r=await authRuntime();await r.c.handleForm(login({authPassword:'old123'}));assert.equal(r.calls[0].data.password,'old123');assert.equal(r.c.session.user.id,'verified-member');});
await test('Wrong password stays signed out and does not fall back to OTP',async()=>{const r=await authRuntime({signInWithPassword:async()=>({error:{code:'invalid_credentials',message:'Invalid login credentials'}})});await r.c.handleForm(login());assert.equal(r.c.session,null);assert.match(r.elements.authLayer.innerHTML,/E-posta veya şifre hatalı/);assert.equal(r.count('signInWithOtp'),0);assert.equal(r.count('signUp'),0);assert.equal(r.count('resend'),0);assert.equal(r.document.getElementById('authEmail').value,email);assert.ok(!r.elements.authLayer.innerHTML.includes(password));});
await test('Network login error keeps retryable password form',async()=>{const r=await authRuntime({signInWithPassword:async()=>{throw new Error('Failed to fetch')}});await r.c.handleForm(login());assert.equal(r.c.session,null);assert.match(r.elements.authLayer.innerHTML,/İnternet bağlantısı/);assert.ok(dom(r.elements.authLayer.innerHTML).querySelector('#authPassword'));});
await test('Login success response without a real session is rejected',async()=>{const r=await authRuntime({signInWithPassword:async()=>({data:{session:null}})});await r.c.handleForm(login());assert.equal(r.c.session,null);assert.match(r.elements.authLayer.innerHTML,/Giriş tamamlanamadı/);});
await test('Duplicate password submissions make one request',async()=>{const gate=deferred();const r=await authRuntime({signInWithPassword:async()=>{await gate.promise;return{data:{session:userSession()}}}});const f=login(),a=r.c.handleForm(f);await r.c.handleForm(f);await r.c.handleClick(button('forgot-password'));gate.resolve();await a;assert.equal(r.count('signInWithPassword'),1);assert.equal(r.count('resetPasswordForEmail'),0);});
await test('Unconfirmed account resumes signup verification without automatically sending another code',async()=>{const r=await authRuntime({signInWithPassword:async()=>({error:{code:'email_not_confirmed',message:'Email not confirmed'}})});await r.c.handleForm(login());assert.equal(r.c.session,null);assert.equal(r.calls.length,1);const d=dom(r.elements.authLayer.innerHTML);assert.ok(d.querySelector('#authOtp'));assert.match(d.body.textContent,/E-posta adresini doğrula/);assert.match(d.body.textContent,/Önceki kodunu/);});
await test('Unconfirmed legacy error text also resumes verification',async()=>{const r=await authRuntime({signInWithPassword:async()=>({error:{message:'Email not confirmed'}})});await r.c.handleForm(login());assert.ok(dom(r.elements.authLayer.innerHTML).querySelector('#authOtp'));assert.equal(r.calls.length,1);});
await test('Unconfirmed user explicitly resends signup mail with no passwordless login request',async()=>{const r=await authRuntime({signInWithPassword:async()=>({error:{code:'email_not_confirmed'}})});await r.c.handleForm(login());await r.c.handleClick(button('resend-otp'));eq(r.calls[1],{name:'resend',data:{type:'signup',email,options:{emailRedirectTo:'com.fittracklabs.mobile://auth-callback'}}});assert.equal(r.count('signInWithOtp'),0);});
await test('Mismatched signup passwords are rejected before registration or email',async()=>{const r=await authRuntime();await r.c.handleForm(signup({authPasswordConfirm:'different'}));assert.equal(r.calls.length,0);assert.match(r.elements.authLayer.innerHTML,/eşleşmiyor/);});
await test('Short signup password and missing consent cannot create accounts',async()=>{const r=await authRuntime();await r.c.handleForm(signup({authPassword:'short',authPasswordConfirm:'short'}));await r.c.handleForm(signup({authConsent:false}));assert.equal(r.calls.length,0);});
await test('Valid signup sends password once, waits for email verification and does not persist it',async()=>{const r=await authRuntime();await r.c.handleForm(signup());assert.equal(r.count('signUp'),1);assert.equal(r.calls[0].data.password,password);assert.equal(r.calls.length,1);assert.equal(r.c.session,null);assert.ok(dom(r.elements.authLayer.innerHTML).querySelector('#authOtp'));assert.ok(![...r.store.values()].some(v=>v.includes(password)));});
await test('Server-confirmed signup session is handled without forced signout or a second OTP email',async()=>{const r=await authRuntime({signUp:async()=>({data:{session:userSession()}})});await r.c.handleForm(signup());assert.equal(r.c.session.user.id,'verified-member');assert.equal(r.calls.length,1);});
await test('Signup resend cooldown prevents extra emails',async()=>{const r=await authRuntime();await r.c.handleForm(signup());await r.c.handleClick(button('resend-otp'));assert.equal(r.count('resend'),0);assert.match(r.elements.authLayer.innerHTML,/60 saniye/);});
await test('Code is verified against original signup email even when read on another device',async()=>{const r=await authRuntime({verifyOtp:async()=>({data:{session:userSession()}})});await r.c.handleForm(signup());await r.c.handleForm(form('verify-otp',{authOtp:'012345'}));eq(r.calls[1],{name:'verifyOtp',data:{email,token:'012345',type:'email'}});assert.equal(r.c.session.user.id,'verified-member');assert.equal(r.count('signInWithOtp'),0);});
await test('Formatted six-digit code can be pasted without losing a leading zero',async()=>{const r=await authRuntime({verifyOtp:async()=>({data:{session:userSession()}})});r.c.renderConfirmation(email,0);const d=dom(r.elements.authLayer.innerHTML),input=d.querySelector('#authOtp');assert.ok(new RegExp('^(?:'+input.getAttribute('pattern')+')$').test('012 345'));await r.c.verifyEmailCode(' 012 345 ');assert.equal(r.calls[0].data.token,'012345');});
await test('Previously issued eight-digit codes are not truncated during server setting rollout',async()=>{const r=await authRuntime({verifyOtp:async()=>({data:{session:userSession()}})});r.c.renderConfirmation(email,0);await r.c.verifyEmailCode('01234567');assert.equal(r.calls[0].data.token,'01234567');});
await test('Five-digit, malformed and overlong codes cannot authenticate',async()=>{const r=await authRuntime();r.c.renderConfirmation(email,0);for(const code of ['12345','12ab56','12345678901'])await assert.rejects(r.c.verifyEmailCode(code),/eksiksiz/);assert.equal(r.calls.length,0);assert.equal(r.c.session,null);});
await test('Expired or wrong code stays on retry screen with no session',async()=>{const r=await authRuntime({verifyOtp:async()=>({error:{code:'otp_expired',message:'Token has expired or is invalid'}})});r.c.renderConfirmation(email,0);await r.c.handleForm(form('verify-otp',{authOtp:'123456'}));assert.equal(r.c.session,null);assert.ok(dom(r.elements.authLayer.innerHTML).querySelector('#authOtp'));assert.match(r.elements.authLayer.innerHTML,/Kod hatalı veya süresi dolmuş/);});
await test('Verification without returned session never activates account',async()=>{const r=await authRuntime();r.c.renderConfirmation(email,0);await assert.rejects(r.c.verifyEmailCode('123456'),/doğrulanamadı/);assert.equal(r.c.session,null);});
await test('Back from confirmation restores password login and discards pending verification',async()=>{const r=await authRuntime();r.c.renderConfirmation(email,0);await r.c.handleClick(button('change-otp-email'));assert.ok(dom(r.elements.authLayer.innerHTML).querySelector('#authPassword'));assert.equal(r.document.getElementById('authEmail').value,email);await assert.rejects(r.c.verifyEmailCode('123456'),/Önce e-posta kodu iste/);assert.equal(r.calls.length,0);});
await test('Passwordless login code requests are not supported by application handlers',async()=>{const r=await authRuntime();await assert.rejects(r.c.requestEmailCode(email,'login'),/şifreni kullan/);assert.equal(r.calls.length,0);});
await test('Password update remains gated by verified recovery',async()=>{const r=await authRuntime();await r.c.handleForm(form('update-password',{newPassword:password,confirmPassword:password}));assert.equal(r.count('updateUser'),0);assert.match(r.elements.authLayer.innerHTML,/Önce e-posta kodunu doğrula/);});
await test('Explicit password recovery verifies recovery code before accepting matching new passwords',async()=>{const r=await authRuntime({verifyOtp:async()=>({data:{session:userSession()}})});await r.c.requestEmailCode(email,'recovery');await r.c.verifyEmailCode('123456');assert.equal(r.calls[0].name,'resetPasswordForEmail');assert.equal(r.calls[1].data.type,'recovery');await r.c.handleForm(form('update-password',{newPassword:password,confirmPassword:'different'}));assert.equal(r.count('updateUser'),0);await r.c.handleForm(form('update-password',{newPassword:password,confirmPassword:password}));assert.equal(r.count('updateUser'),1);assert.equal(r.count('signInWithOtp'),0);});
await test('Existing persisted sessions are resumed on boot without password or new email',async()=>{const r=await authRuntime({getSession:async()=>({data:{session:userSession()}})});r.window.FITTRACK_CONFIG.localPreviewOnDesktop=false;let options;r.window.supabase={createClient:(url,key,o)=>{options=o;return r.client;}};await r.c.boot();assert.equal(r.count('getSession'),1);assert.equal(r.count('signInWithPassword'),0);assert.equal(r.count('signInWithOtp'),0);assert.equal(r.c.session.user.id,'verified-member');assert.equal(options.auth.storageKey,'fittrack-beta-010-auth');assert.equal(options.auth.persistSession,true);});
await test('Normal login still works when every email sending API is unavailable',async()=>{const fail=async()=>{throw new Error('Email service unavailable')};const r=await authRuntime({signInWithOtp:fail,resend:fail,resetPasswordForEmail:fail});await r.c.handleForm(login());assert.equal(r.c.session.user.id,'verified-member');assert.equal(r.calls.length,1);});
await test('Templates use complete code; configuration sets six digits and leaves Magic Link alone',()=>{for(const name of ['confirmation','recovery']){const html=fs.readFileSync(path.join(__dirname,'../supabase/templates',name+'.html'),'utf8');assert.ok(html.includes('{{ .Token }}'));assert.ok(!html.includes('ConfirmationURL'));assert.equal(dom(html).querySelectorAll('a[href]').length,0);}const r=spawnSync('python3',[path.join(__dirname,'../scripts/configure_auth_templates.py')],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const p=JSON.parse(r.stdout);assert.equal(p.mailer_otp_length,6);assert.equal(Object.keys(p).length,5);assert.ok(!Object.keys(p).some(k=>k.includes('magic_link')));});
fs.mkdirSync(path.join(__dirname,'../test-results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../test-results/auth-0116.json'),JSON.stringify({method:'Node VM plus Linkedom DOM; mocked Supabase Auth; no live email or physical/browser test',results},null,2));for(const r of results)console.log(r.status,r.name,r.error||'');console.log(JSON.stringify({total:results.length,passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length}));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
