'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {parseHTML}=require('linkedom');
const {fresh,clone,runtime,setupWorkout,cloudRuntime}=require('./review/harness.cjs');
const results=[];const eq=(a,b)=>assert.deepEqual(clone(a),clone(b));
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message,stack:e.stack.split('\n').slice(0,4)});}}
const dom=html=>parseHTML('<html><body>'+html+'</body></html>').document;
(async()=>{
await test('Trainer unassign → partial finish → new assignment can start',()=>{const r=fresh(),p=setupWorkout(r);const w=r.app.state.currentWorkout;const id=w.syncId;w.assignmentCloudId='40000000-0000-4000-8000-000000000001';r.app.getCurrentLog().completedAt=new Date().toISOString();r.app.getCurrentLog().weight='30';r.app.getCurrentLog().reps='10';r.app.state.assignments=[];r.app.state.assignment=null;r.app.state.customPrograms=[];r.app.refreshPrograms();r.app.startWorkout();assert.equal(r.app.currentProgram().id,p.id);r.app.finishWorkout(true);assert.equal(r.app.state.history[0].syncId,id);assert.equal(r.app.state.history[0].assignmentCloudId,w.assignmentCloudId);r.click('summary-home');assert.equal(r.app.state.currentWorkout,null);setupWorkout(r,{id:'new-plan'});r.app.startWorkout();assert.equal(r.app.currentProgram().id,'new-plan');});
await test('Unassigned paused session can be canceled and stays canceled after remote replay',()=>{const r=fresh();setupWorkout(r);r.app.pauseWorkout();const stale=clone(r.app.getCloudSnapshot());r.app.state.assignments=[];r.app.state.assignment=null;r.app.cancelWorkout();assert.ok(r.app.state.closedWorkoutIds[stale.currentWorkout.syncId]);r.app.applyRemoteSnapshot(stale);assert.equal(r.app.state.currentWorkout,null);assert.equal(r.app.state.history.length,0);});
await test('Legacy missing plan preserves actual completed logs in recovery',()=>{const r=fresh();setupWorkout(r);const w=clone(r.app.state.currentWorkout);delete w.programSnapshot;w.programId='gone';w.logs={'0':{'0':{completedAt:new Date().toISOString(),weight:'22',reps:'8'},'1':{weight:'22',reps:'8'}}};r.app.state.customPrograms=[];r.app.refreshPrograms();r.app.state.currentWorkout=r.app.normalizeCurrentWorkout(w);r.app.startWorkout();assert.ok(r.app.state.currentWorkout.orphaned);const d=dom(r.elements.flowLayer.innerHTML);assert.ok(d.querySelector('[data-action="confirm-cancel"]'));r.app.finishWorkout(true);assert.equal(r.app.state.history[0].totalSets,1);assert.equal(r.app.state.history[0].exercises[0].sets[0].weight,'22');});
await test('Empty missing-plan session has a cancel path and cannot save empty history',()=>{const r=fresh();setupWorkout(r);const w=clone(r.app.state.currentWorkout);delete w.programSnapshot;w.programId='gone';r.app.state.customPrograms=[];r.app.refreshPrograms();r.app.state.currentWorkout=r.app.normalizeCurrentWorkout(w);r.app.startWorkout();assert.ok(dom(r.elements.flowLayer.innerHTML).querySelector('[data-action="finish-early"]').disabled);r.app.cancelWorkout();assert.equal(r.app.state.currentWorkout,null);});
await test('Newer idle snapshot from another device does not close active workout',()=>{const r=fresh();setupWorkout(r);const id=r.app.state.currentWorkout.syncId;r.app.applyRemoteSnapshot({currentWorkout:null,workoutUpdatedAt:'2099-01-01T00:00:00Z',_cloudMeta:{clientUpdatedAt:'2099-01-01T00:00:00Z'},history:[]});assert.equal(r.app.state.currentWorkout.syncId,id);});
await test('Cancel on second device explicitly closes original device session',()=>{const a=fresh();setupWorkout(a);const b=fresh();b.app.applyRemoteSnapshot(clone(a.app.getCloudSnapshot()));b.app.cancelWorkout();a.app.applyRemoteSnapshot(clone(b.app.getCloudSnapshot()));assert.equal(a.app.state.currentWorkout,null);});
await test('Rapid workout changes receive monotonically increasing timestamps',()=>{const r=fresh();setupWorkout(r);r.app.saveState();const a=r.app.state.currentWorkout.updatedAt;r.app.getCurrentLog().weight='31';r.app.saveState();assert.ok(r.app.state.currentWorkout.updatedAt>a);});
await test('Active workout snapshot is independent from later program edits',()=>{const r=fresh();const p=setupWorkout(r);const old=r.app.currentExercises()[0].name;p.days[0].exercises[0].name='Changed';r.app.refreshPrograms();assert.equal(r.app.currentExercises()[0].name,old);});
await test('Unknown assignment does not turn into starter or become startable',()=>{const r=fresh();r.app.state.assignments=[r.app.normalizeAssignment({programId:'missing-plan'},0,'Coach')];r.app.state.assignment=r.app.state.assignments[0];assert.equal(r.app.state.assignments[0].programId,'missing-plan');assert.equal(r.app.assignedPrograms().length,0);r.app.startWorkout();assert.equal(r.app.state.currentWorkout,null);});
await test('Clock excludes paused time and pauses at a stable value',()=>{const r=fresh();setupWorkout(r);const w=r.app.state.currentWorkout;const now=Date.now();w.startedAt=new Date(now-120000).toISOString();w.totalPausedMs=10000;w.status='paused';w.pausedAt=now-30000;assert.equal(r.app.elapsedSeconds(w),80);assert.equal(r.app.workoutClock(),'01:20');r.app.renderPaused();assert.equal(dom(r.elements.flowLayer.innerHTML).querySelector('[data-workout-clock]').textContent,'01:20');});
await test('Set type, rep target and elapsed time render as distinct readable fields',()=>{const r=fresh();setupWorkout(r);r.app.state.currentWorkout.programSnapshot.days[0].exercises[0].setPlan[0].type='drop';r.app.renderWorkout();const d=dom(r.elements.flowLayer.innerHTML);assert.ok(d.querySelector('.set-kind-drop'));assert.ok(d.querySelector('.rep-target'));assert.ok(d.querySelector('[data-workout-clock]'));});
await test('Committed deletion acknowledged once and scoped to originating gym',async()=>{let calls=0;const r=await cloudRuntime({rpc:async()=>{calls++;return{data:true}}});await r.c.deleteWorkout('50000000-0000-4000-8000-000000000001');const acks=[...r.store].filter(([k])=>k.startsWith('fittrack-deletion-acks:'));assert.equal(acks.length,1);assert.ok(acks[0][0].endsWith(':gym-A'));const snapshot={deletedHistoryIds:['50000000-0000-4000-8000-000000000001']};r.c.setContext({bridge:{setCloudStatus(){},getCloudSnapshot:()=>clone(snapshot),getWorkoutRecords:()=>[]}});r.c.scheduleStateSync(true);r.timer(0);await Promise.resolve();assert.ok(!r.c.queue().some(x=>x.type==='workout-delete'));});

function editorFixture(r) { const p=setupWorkout(r);r.app.closeCurrentWorkout();r.app.ui.editorDraft=r.app.editorDraftFromProgram(p,false);r.app.ui.editorDraft.name='Draft with all values';r.app.ui.studioStep=3;const move=r.app.ui.editorDraft.days[0].exercises[0];move.coachNote='Keep exact note';move.setPlan[0].targetWeight='33';return r.app.ui.editorDraft; }
await test('Exercise delete requires confirmation and undo restores exact data',()=>{const r=fresh();const draft=editorFixture(r),before=clone(draft.days);r.app.removeStudioExercise(0);eq(r.app.ui.editorDraft.days,before);r.click('editor-confirm-remove');assert.equal(r.app.ui.editorDraft.days[0].exercises.length,0);r.click('editor-undo');eq(r.app.ui.editorDraft.days,before);});
await test('Day deletion undo restores day order, notes and set plans',()=>{const r=fresh();editorFixture(r);r.app.addEditorDay();const draft=r.app.ui.editorDraft;draft.days[1].exercises.push(r.app.cloneExerciseDefinition(draft.days[0].exercises[0]));const before=clone(draft.days);r.app.removeEditorDay();eq(r.app.ui.editorDraft.days,before);r.click('editor-confirm-remove');assert.equal(r.app.ui.editorDraft.days.length,1);r.click('editor-undo');eq(r.app.ui.editorDraft.days,before);});
await test('Set deletion undo restores the removed target/type/rest fields',()=>{const r=fresh();const d=editorFixture(r);r.app.ui.studioExerciseIndex=0;const before=clone(d.days);r.app.changeStudioSetCount(-1);eq(r.app.ui.editorDraft.days,before);r.click('editor-confirm-remove');assert.equal(r.app.ui.editorDraft.days[0].exercises[0].sets,before[0].exercises[0].sets-1);r.click('editor-undo');eq(r.app.ui.editorDraft.days,before);});
await test('Dirty editor keep-and-exit survives a new app instance',()=>{const r=fresh();editorFixture(r);const before=clone(r.app.ui.editorDraft.days);r.app.requestEditorExit(()=>{});r.click('editor-exit-keep');assert.equal(r.app.ui.editorDraft,null);const n=runtime(null,r.store);n.app.restoreEditorRecovery();eq(n.app.ui.editorDraft.days,before);});
await test('Deleting current account removes its gym and draft caches only',()=>{const r=fresh();r.app.activateAccount('user-A','a@example.invalid');r.app.activateGym('gym-A');editorFixture(r);r.app.saveEditorRecovery();r.store.set('fittrack-deletion-acks:user-A:gym-A','["one"]');r.store.set('fittrack-deletion-acks:user-B:gym-B','["keep"]');r.app.clearCurrentAccountData();assert.ok(![...r.store.keys()].some(k=>k.includes('user-A')));assert.equal(r.store.get('fittrack-deletion-acks:user-B:gym-B'),'["keep"]');assert.equal(r.app.ui.editorDraft,null);});
await test('Real bootstrap removing all assignments preserves active workout controls',()=>{const r=fresh();r.app.activateAccount('member','m@example.invalid');setupWorkout(r);const id=r.app.state.currentWorkout.syncId;r.app.applyCloudBootstrap({user:{id:'member'},profile:{display_name:'Test Member'},gym:{id:'gym-A',name:'Gym A',created_by:'coach'},membership:{role:'member'},profiles:[],members:[],programs:[],assignments:[],workouts:[],snapshots:[],messages:[],workoutDeletions:[]});assert.equal(r.app.state.assignments.length,0);assert.equal(r.app.state.currentWorkout.syncId,id);r.app.startWorkout();r.app.confirmCancel();assert.ok(dom(r.elements.sheetLayer.innerHTML).querySelector('[data-action="cancel-workout"]'));r.click('cancel-workout');assert.equal(r.app.state.currentWorkout,null);});

await test('Program undo survives stale deletion snapshot and reload',()=>{const r=fresh();const p=setupWorkout(r);r.app.closeCurrentWorkout();r.app.state.assignments=[];r.app.state.assignment=null;r.app.deleteStudioProgram(p.id);const deleted=clone(r.app.getCloudSnapshot());assert.ok(!r.app.state.customPrograms.some(x=>x.id===p.id));r.app.undoProgramDelete();assert.ok(r.app.state.customPrograms.some(x=>x.id===p.id));r.app.applyRemoteSnapshot(deleted);assert.ok(r.app.state.customPrograms.some(x=>x.id===p.id));r.app.saveState();const n=runtime(null,r.store);assert.ok(n.app.state.customPrograms.some(x=>x.id===p.id));});
fs.mkdirSync(path.join(__dirname,'../test-results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../test-results/hotfix-0114.json'),JSON.stringify({method:'Node VM plus Linkedom DOM parsing; mocked Auth/network; no real email or physical/browser tests',results},null,2));for(const r of results)console.log(r.status,r.name,r.error||'');console.log(JSON.stringify({total:results.length,passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length}));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
