"use strict";
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const {parseHTML} = require('linkedom');
const {fresh,setupWorkout,clone,runtime} = require('./review/harness.cjs');
const root=path.resolve(__dirname,'..'),results=[];
const dom=html=>parseHTML('<html><body>'+html+'</body></html>').document;
function test(name,run){try{run();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message.slice(0,1100)});}}
function record(r,index=0,date=r.app.todayKey(),status='completed'){
 return r.app.normalizeHistoryItem({id:'member-test-'+index,date,name:'Test session',status,duration:20,exercises:[{id:'bench-press',name:'Bench Press',requiresWeight:true,sets:[{weight:'60',reps:'10',completedAt:new Date().toISOString()}]}]});
}
function player(r){r.app.renderWorkout();return dom(r.elements.flowLayer.innerHTML);}
test('New account and empty history have no earned badges',()=>{const r=fresh();assert.equal(r.app.achievements().filter(x=>x.earned).length,0);assert.equal(r.app.achievements().length,7);});
test('Only completed real workouts count; partial, cancelled, demo, empty and future records do not',()=>{
 const r=fresh();r.app.state.history=[record(r,1),record(r,2,undefined,'partial'),record(r,3),record(r,4),record(r,5,r.app.addDays(r.app.todayKey(),1)),record(r,6)];
 r.app.state.history[2].isDemo=true;r.app.state.history[3].exercises=[];r.app.state.history[5].status='cancelled';
 assert.equal(r.app.achievementStats().workouts,1);assert.equal(r.app.achievements().filter(x=>x.earned).length,1);
});
test('Nine then ten workouts unlock exactly the ten-workout milestone',()=>{const r=fresh();r.app.state.history=Array.from({length:9},(_,i)=>record(r,i));assert.equal(r.app.achievements().find(x=>x.id==='ten-workouts').earned,false);r.app.state.history.push(record(r,9));assert.equal(r.app.achievements().find(x=>x.id==='ten-workouts').earned,true);});
test('Duplicate sync records do not grant extra badges',()=>{const r=fresh(),one=record(r);r.app.state.history=[one,clone(one),clone(one)];assert.equal(r.app.achievementStats().workouts,1);});
test('Every workout milestone has correct threshold and capped progress',()=>{for(const n of [1,10,25,50,100]){const r=fresh();r.app.state.history=Array.from({length:n},(_,i)=>record(r,i));for(const b of r.app.achievements().filter(x=>x.metric==='workouts')){assert.equal(b.earned,n>=b.goal);assert.ok(b.value<=b.goal);}}});
test('Multiple workouts in one week count as a single active week',()=>{const r=fresh();r.app.state.history=Array.from({length:10},(_,i)=>record(r,i));assert.equal(r.app.achievementStats().weeks,1);});
test('Four-week badge survives a later break in activity',()=>{const r=fresh(),m=r.app.mondayFor(r.app.todayKey());r.app.state.history=Array.from({length:4},(_,i)=>record(r,i,r.app.addDays(m,-(i+8)*7)));assert.equal(r.app.calculateStreak(),0);assert.equal(r.app.achievements().find(x=>x.id==='four-weeks').earned,true);});
test('A missing calendar week breaks the achievement streak',()=>{const r=fresh(),m=r.app.mondayFor(r.app.todayKey());r.app.state.history=[0,1,3,4].map((n,i)=>record(r,i,r.app.addDays(m,-n*7)));assert.equal(r.app.achievementStats().weeks,2);});
test('Weekly achievement handles year boundaries and unordered records',()=>{const r=fresh();r.app.state.history=['2025-12-22','2026-01-12','2025-12-29','2026-01-05'].map((d,i)=>record(r,i,d));assert.equal(r.app.achievementStats().weeks,4);});
test('Editing history to partial recalculates eligibility',()=>{const r=fresh();r.app.state.history=[record(r)];assert.ok(r.app.achievements()[0].earned);r.app.state.history[0].status='partial';assert.equal(r.app.achievements()[0].earned,false);});
test('Achievements survive storage reload and stay separate between accounts',()=>{const r=fresh();r.app.activateAccount('member-A','a@example.invalid');r.app.state.history=[record(r)];r.app.saveState();const n=runtime(null,r.store);assert.ok(n.app.achievements()[0].earned);n.app.activateAccount('member-B','b@example.invalid');assert.equal(n.app.achievements()[0].earned,false);n.app.activateAccount('member-A','a@example.invalid');assert.ok(n.app.achievements()[0].earned);});
test('All badges and rule details can be opened and closed through actions',()=>{const r=fresh();r.click('achievements');assert.equal(dom(r.elements.sheetLayer.innerHTML).querySelectorAll('[data-action="achievement-detail"]').length,7);r.click('achievement-detail',{id:'four-weeks'});assert.ok(dom(r.elements.sheetLayer.innerHTML).body.textContent.includes('her birinde en az bir'));r.click('close-sheet');assert.equal(r.elements.sheetLayer.classList.contains('active'),false);});
test('Existing Progress filters, graphs and history remain alongside badges',()=>{const r=fresh();r.app.state.history=[record(r)];for(const range of ['days','weeks','months']){r.app.ui.progressRange=range;r.app.renderProgress();const d=dom(r.elements.screen.innerHTML);assert.deepEqual([...d.querySelectorAll('[data-action="progress-range"]')].map(x=>x.textContent),['7 gün','4 hafta','6 ay']);assert.ok(d.querySelector('.lift-chart'));assert.ok(d.querySelector('.history-list'));assert.equal(d.querySelectorAll('.achievements-section').length,1);}});
test('Member home uses a real assigned program and never invents a program when empty',()=>{const r=fresh();r.app.state.assignments=[];r.app.state.assignment=null;r.app.renderHome();assert.ok(r.elements.screen.innerHTML.includes('Henüz antrenman atanmadı'));assert.equal(dom(r.elements.screen.innerHTML).querySelector('[data-action="start-assigned-program"]'),null);const p=setupWorkout(r);r.app.closeCurrentWorkout();r.app.renderHome();const d=dom(r.elements.screen.innerHTML);assert.equal(d.querySelector('[data-action="start-assigned-program"]').dataset.programId,p.id);assert.equal(d.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'),'0');});
test('Featured card preserves active workout progress and paused status',()=>{const r=fresh();setupWorkout(r);r.app.getCurrentLog().completedAt=new Date().toISOString();r.app.pauseWorkout();r.app.renderHome();const d=dom(r.elements.screen.innerHTML);assert.ok(d.body.textContent.includes('Duraklatıldı'));assert.equal(d.querySelector('[role="progressbar"]').getAttribute('aria-valuenow'),'33');assert.ok(d.querySelector('[data-action="start"]'));});
test('Removed assignment keeps recovery and cancel controls on home',()=>{const r=fresh();const p=setupWorkout(r);r.app.state.assignments=[];r.app.state.assignment=null;r.app.state.customPrograms=[];r.app.refreshPrograms();r.app.renderHome();const d=dom(r.elements.screen.innerHTML);assert.ok(d.body.textContent.includes(p.name));assert.ok(d.querySelector('[data-action="start"]'));assert.ok(d.querySelector('[data-action="confirm-cancel"]'));r.click('start');r.click('confirm-cancel');r.click('cancel-workout');assert.equal(r.app.state.currentWorkout,null);});
test('Multiple assignments remain accessible; opening home does not select a different one',()=>{const r=fresh();const p=setupWorkout(r);r.app.closeCurrentWorkout();const q=r.app.normalizeCustomProgram({...clone(p),id:'second-plan',name:'Second program'});r.app.state.customPrograms.push(q);r.app.refreshPrograms();r.app.state.assignments.push(r.app.normalizeAssignment({programId:q.id},1,'Coach'));const before=r.app.state.selectedProgramId;r.app.renderHome();assert.ok(dom(r.elements.screen.innerHTML).querySelector('.member-all-programs[data-tab="programs"]'));assert.equal(r.app.state.selectedProgramId,before);r.click('nav',{tab:'programs'});assert.equal(dom(r.elements.screen.innerHTML).querySelectorAll('.assigned-program-card').length,2);});
// 0.12.0 changes the staff home by request; keep the member/staff separation gate.
test('Staff summary remains separate from the member workout home',()=>{const r=fresh();r.app.state.cloud.role='trainer';r.app.renderHome();assert.equal(dom(r.elements.screen.innerHTML).querySelector('.member-home'),null);assert.ok(dom(r.elements.screen.innerHTML).querySelector('.trainer-home'));});
test('Member stylesheet parses and has no selectors that restyle trainer screens',()=>{
 const sheet=require('cssom').parse(fs.readFileSync(path.join(root,'member-ui.css'),'utf8')),selectors=[];
 const visit=rules=>{for(const rule of rules){if(rule.cssRules)visit(rule.cssRules);if(rule.selectorText)selectors.push(...rule.selectorText.split(',').map(s=>s.trim().replace(/::[\w-]+/g,'')));}};visit(sheet.cssRules);
 const r=fresh();r.app.state.cloud.role='trainer';r.app.renderHome();const screens=[r.elements.screen.innerHTML];r.app.renderTrainerPanel();screens.push(r.elements.flowLayer.innerHTML);for(const member of r.app.state.trainer.members){r.app.renderTrainerMember(member.id);screens.push(r.elements.flowLayer.innerHTML);}
 for(const html of screens){const d=dom(html);for(const selector of selectors)assert.ok(!d.querySelector(selector),'Unexpected trainer style: '+selector);}
});
test('Exercise media has no playback, angle or rotation controls',()=>{const r=fresh();setupWorkout(r);const d=player(r),media=d.querySelector('.exercise-visual');assert.equal(media.querySelectorAll('img').length,1);assert.equal(media.querySelectorAll('button,video,.gif-badge,.visual-tags').length,0);assert.equal(media.textContent,'');});
test('Workout name, elapsed time, exercise count and set count render separately',()=>{const r=fresh(),p=setupWorkout(r);const d=player(r);assert.equal(d.querySelector('.member-player-top h1').textContent,p.name);assert.equal(d.querySelectorAll('[data-workout-clock]').length,1);assert.deepEqual([...d.querySelectorAll('.member-player-position strong')].map(x=>x.textContent),['Hareket 1 / 1','Set 1 / 3']);});
test('Drop set instructions are distinct from actual result fields and omit rest copy',()=>{const r=fresh();setupWorkout(r);const item=r.app.currentExercise();item.setPlan[0].type='drop';item.setPlan[0].repsTarget='8–10';item.setPlan[0].targetWeight='42.5';const d=player(r);assert.equal(d.querySelector('.set-kind-drop').textContent,'Drop set');assert.equal(d.querySelector('.rep-target').textContent,'8–10');assert.ok(d.body.textContent.includes('42.5 kg'));assert.ok(d.querySelector('[data-log-field="reps"]'));assert.ok(!/dinlenme/i.test(d.body.textContent));});
test('Instructions open by default and entry scrolls last while only completion stays in the dock',()=>{const r=fresh();setupWorkout(r);r.app.currentExercise().cues=Array.from({length:15},(_,i)=>'Adım '+i+' açıklama '.repeat(50));const d=player(r),details=d.querySelector('details.workout-instructions'),main=d.querySelector('.member-player-scroll'),entry=d.querySelector('#entryCard'),dock=d.querySelector('.member-player-dock');assert.equal(details.hasAttribute('open'),true);assert.equal(details.querySelectorAll('li').length,15);assert.ok(details.querySelector('summary').textContent.includes('15 adım'));assert.ok(main.contains(details));assert.ok(main.lastElementChild===entry);assert.ok(entry.querySelector('[data-log-field="weight"]'));assert.ok(entry.querySelector('[data-log-field="reps"]'));assert.ok(!dock.contains(entry));assert.ok(!dock.querySelector('input'));assert.equal(dock.querySelectorAll('button').length,1);assert.ok(dock.querySelector('[data-action="complete-set"]'));});
test('Weight and repetitions stay editable with steppers and no mandatory entry',()=>{const r=fresh();setupWorkout(r);player(r);r.click('adjust-log',{field:'weight',delta:'2.5'});r.click('adjust-log',{field:'reps',delta:'1'});assert.equal(r.app.getCurrentLog().weight,'2.5');assert.equal(r.app.getCurrentLog().reps,'1');r.app.getCurrentLog().weight='';r.app.getCurrentLog().reps='';r.click('complete-set');assert.ok(r.app.getCurrentLog().completedAt);});
test('Invalid values do not advance or complete a set',()=>{const r=fresh();setupWorkout(r);player(r);r.app.getCurrentLog().reps='101';r.click('complete-set');assert.ok(!r.app.getCurrentLog().completedAt);assert.equal(r.app.state.currentWorkout.setIndex,0);});
test('Completing and revisiting a set updates without duplicate completion',()=>{const r=fresh();setupWorkout(r);r.app.currentExercise().setPlan[0].rest=0;r.click('complete-set');assert.equal(r.app.state.currentWorkout.setIndex,1);assert.equal(r.app.completedSetCount(r.app.state.currentWorkout),1);r.click('previous-set');assert.equal(r.app.state.currentWorkout.setIndex,0);r.app.renderWorkout();assert.equal(dom(r.elements.flowLayer.innerHTML).querySelector('[data-action="complete-set"]').textContent,'Seti güncelle');r.click('complete-set');assert.equal(r.app.completedSetCount(r.app.state.currentWorkout),1);});
test('No weight field is shown for a bodyweight movement',()=>{const r=fresh();setupWorkout(r,{moves:[r.app.cloneExerciseDefinition(r.app.catalogExercises()[3])]});const d=player(r);assert.equal(d.querySelector('[data-log-field="weight"]'),null);assert.ok(d.querySelector('[data-log-field="reps"]'));});
test('Exercise guidance and names escape user-authored HTML',()=>{const r=fresh();setupWorkout(r);r.app.currentExercise().name='<img src=x onerror=alert(1)>';r.app.currentExercise().cues=['<script>alert(1)</script>'];const d=player(r);assert.equal(d.querySelectorAll('script,[onerror]').length,0);assert.ok(d.querySelector('li').textContent.includes('<script>'));});
test('All six themes render the new member screens without changing selection',()=>{for(const theme of ['volt-discipline','crimson-graphite','plum-night','redline-editorial','rosewood-strength','sage-motion']){const r=fresh();setupWorkout(r);r.app.state.theme=theme;r.app.render();player(r);r.app.renderProgress();assert.equal(r.app.state.theme,theme);assert.equal(r.document.documentElement.dataset.theme,theme);}});
test('New CSS is shipped and cached; dock is outside scrolling content with 20px counters',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),build=fs.readFileSync(path.join(root,'scripts/build_android.py'),'utf8'),css=fs.readFileSync(path.join(root,'member-ui.css'),'utf8');for(const s of [html,sw,build])assert.ok(s.includes('member-ui.css'));assert.match(css,/grid-template-rows: auto minmax\(0, 1fr\) auto/);assert.match(css,/\.member-player-position strong \{ font-size: 20px/);assert.ok(!/#[0-9a-fA-F]{3,8}\b/.test(css));});
fs.mkdirSync(path.join(root,'test-results'),{recursive:true});fs.writeFileSync(path.join(root,'test-results/member-ui-0117.json'),JSON.stringify({method:'Node VM + Linkedom DOM; not a rendered browser or physical phone test',results},null,2));
for(const r of results)console.log(r.status,r.name,r.error||'');console.log(JSON.stringify({total:results.length,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length}));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
